server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_0909?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider
version: UserProvider01